name: Simple AndResGuard Release

on:
  push:
    tags: ['v*']
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        
    - name: Build APK
      run: ./gradlew assembleRelease
      
    - name: Download AndResGuard
      run: |
        wget https://github.com/shwenzhang/AndResGuard/releases/download/2.2.3/AndResGuard-cli-2.2.3.jar
        
    - name: Obfuscate APK
      run: |
        java -jar AndResGuard-cli-2.2.3.jar \
          app/build/outputs/apk/release/app-release.apk \
          -out app/build/outputs/apk/obfuscated/
          
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        token: ${{ secrets.RELEASE_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./app/build/outputs/apk/obfuscated/app-release_obfuscated.apk
        asset_name: app-obfuscated.apk
        asset_content_type: application/vnd.android.package-archive